export enum MaintainerrEvent {
  RuleHandler_Started = 'rule_handler.started',
  RuleHandler_Progressed = 'rule_handler.progressed',
  RuleHandler_Finished = 'rule_handler.finished',
  RuleHandler_Failed = 'rule_handler.failed',
  CollectionHandler_Started = 'collection_handler.started',
  CollectionHandler_Progressed = 'collection_handler.progressed',
  CollectionHandler_Finished = 'collection_handler.finished',
  CollectionHandler_Failed = 'collection_handler.failed',
  CollectionMedia_Added = 'collection_media.added',
  CollectionMedia_Removed = 'collection_media.removed',
  CollectionMedia_Handled = 'collection_media.handled',
  Notifications_Fire = 'agents.notify',
  Collection_Created = 'collection.created',
  Collection_Updated = 'collection.updated',
  Collection_Deleted = 'collection.deleted',
  RuleGroup_Created = 'rulegroup.created',
  RuleGroup_Updated = 'rulegroup.updated',
  RuleGroup_Deleted = 'rulegroup.deleted',
  Settings_Updated = 'settings.updated',
}
